seed:
  - count: 100
    skip: true
    command:
      INSERT INTO public."Users" ("CreatedBy","Created","FirstName","LastName","Email","Phone","InterfaceTimeZone","RequestedAccessControlGroup","AccessControlGroup","Disabled")
      Values (-1, NOW(), '<@first@>','<@last@>','!1.!2@<@domain@>','<@phone@>', '<@pickone#["AEST","AWST","LHST","ACST"]@>', <@pickone#[0,1,2,3,4]@>, <@pickone#[0,1,2,3,4]@>, false)
  - count: 100
    skip: false
    command:
      INSERT INTO public."Notes" ("CreatedBy", "Created", "LastModifiedBy", "LastModified", "Title", "OwnerId", "SessionId", "DeviceLatitude", "DeviceLongitude",
      "DeclaredStart", "DeclaredLatitude", "DeclaredLongitude", "Body", "IsPrivate", "IsQuick", "DeclaredLocation", "ProtectiveMarkingId", "Keywords")
      Values ('<@integer#{"min":4, "max":114 }@>', NOW(),'<@integer#{"min":4, "max":114 }@>', NOW(),'<@sentence@>', <@integer#{"min":4, "max":114 }@>,0, <@latitude@>, <@longitude@>,
      NOW(),<@latitude@>,<@longitude@>, '<@paragraph#{"sentences":5}@>',<@bool@>, <@bool@>, '<@word@>', <@integer#{"min":4, "max":4 }@>, '{}')
