seed:
  - name: Create users
    count: 100
    skip: false
    command:
      INSERT INTO public."Users" ("CreatedBy","Created","FirstName","LastName","Email","Phone","InterfaceTimeZone","RequestedAccessControlGroup","AccessControlGroup","Disabled")
      Values (-1, NOW(), '<@word@>','<@word@>','!1.!2@<@domain@>','<@phone@>', '<@pickone#["AEST","AWST","LHST","ACST"]@>', <@pickone#[0,1,2,3,4]@>, <@pickone#[0,1,2,3,4]@>, false)
  - name: Create Notes
    count: 100
    skip: false
    command:
      INSERT INTO public."Notes" ("CreatedBy", "Created", "LastModifiedBy", "LastModified", "Title", "OwnerId", "SessionId", "DeviceLatitude", "DeviceLongitude",
      "DeclaredStart", "DeclaredLatitude", "DeclaredLongitude", "Body", "IsPrivate", "IsQuick", "DeclaredLocation", "ProtectiveMarkingId", "Keywords")
      Values ('<@integer#{"min":1, "max":100 }@>', NOW(),'<@integer#{"min":1, "max":100 }@>', NOW(),'<@sentence@>', <@integer#{"min":1, "max":100 }@>,0, <@latitude@>, <@longitude@>,
      NOW(),<@latitude@>,<@longitude@>, '<@paragraph#{"sentences":5}@>',<@bool@>, <@bool@>, '<@word@>', <@integer#{"min":1, "max":4 }@>, '{}')
